### PR TITLE
Create MolNet_Benchmark_Tutorial.ipynb

### PR DESCRIPTION
**Pull request by ncfrey**
I wrote a brief tutorial that shows how to run a MolNet benchmark in Google Colab. This was helpful to me to set up a consistent environment and run on the GPU. 

If it would be helpful, I'd like to add the tutorial to the repo. Any feedback is welcome!

CCing @mufeili @rbharath

### CODE REVIEW

**Review by rbharath — APPROVED** [review]
This is excellent! I really like the instructions :). I think this will make onboarding other folks to the benchmarks more useful.

Will go ahead and merge in after @mufeili has had a chance to take a look

**Comment by mufeili** [comment]
Can we replace

```ipython
!conda install -c dglteam dgl-cuda11.0 dgllife
```

with

```ipython
!conda install -c dglteam dgl-cuda11.0
!pip install dgllife
```

I deprecated the conda distributions for DGL-LifeSci since 0.2.7.

**Comment by mufeili** [comment]
Can you explain what is `/content`?

**Comment by mufeili** [comment]
"hyperparam" -> "hyperparameter"

**Comment by mufeili** [comment]
"The hyperparam search space can be modified in the molnet python script if desired." Can you specify the exact script name(s)?

**Comment by mufeili** [comment]
For "16 different models", it's not clear what are the 16 models as only RF and GraphConv were introduced. It's probably better to say "16 RF models with different hyperparameters".

**Comment by mufeili** [comment]
I'm good otherwise. Great job!

**Comment by ncfrey** [comment]
> Can you explain what is `/content`?

This was left in unnecessarily, I've removed it.

> For "16 different models", it's not clear what are the 16 models as only RF and GraphConv were introduced. It's probably better to say "16 RF models with different hyperparameters".

Thanks for pointing this out, I've changed the text to read: After training the random forest model with 16 different hyperparameter configurations (and repeating each 3 times to collect statistics for the validation and test errors)

I've updated the tutorial to address @mufeili's comments. Thanks for the feedback!

**Pull request merged**
