### PR TITLE
Lipo dataset added

### PR DESCRIPTION
**Pull request by yuanqidu**

### CODE REVIEW

**Review by rbharath — APPROVED** [review]
Looks good to me!

@mufeili Do you want to take a quick look as well?

**Comment by mufeili** [comment]
Looks good to me. Can you add a new section "Materials Science" in `README.md` and move the results for HOPV there?

**Comment by yuanqidu** [comment]
Sure. Updated.

**Comment by yuanqidu** [comment]
Sure. Updated

**Comment by mufeili** [comment]
@rbharath I'm good and you may go ahead and merge it.

**Pull request merged**
